In [12]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [2]:
original_data = pd.read_csv("Loan_default.csv")

In [3]:
original_data.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [10]:
print(original_data.dtypes)
print(len(original_data))

LoanID                str
Age                 int64
Income              int64
LoanAmount          int64
CreditScore         int64
MonthsEmployed      int64
NumCreditLines      int64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education             str
EmploymentType        str
MaritalStatus         str
HasMortgage           str
HasDependents         str
LoanPurpose           str
HasCoSigner           str
Default             int64
dtype: object
255347

In [15]:
#Just numerical
y=original_data['CreditScore']
x=original_data[['Age',
                 'Income',
                 'MonthsEmployed',
                 'NumCreditLines',
                 'InterestRate',
                 'LoanTerm',
                 'DTIRatio']]
model1=LinearRegression()
model1.fit(x,y)

LinearRegression()

In [16]:
model1.coef_

array([-5.87735192e-03, -5.83376742e-06,  2.84188570e-03,  1.65730082e-03,
        1.03379955e-02,  1.05983798e-02, -7.19430839e-01])

In [17]:
model1.score(x, y)

5.2841199278397255e-06

In [26]:
encoder = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

In [27]:
cateogorical = ['Education',
                'EmploymentType',
                'MaritalStatus',
                'HasMortgage',
                'HasDependents',
                'LoanPurpose',
                'HasCoSigner',
                'Default']

In [29]:
encode_var = encoder.fit_transform(original_data[cateogorical])
encode_var_df = pd.DataFrame(encode_var,columns=encoder.get_feature_names_out(cateogorical))
encode_var_df

,Education_Bachelor's,Education_High School,Education_Master's,Education_PhD,EmploymentType_Full-time,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Divorced,MaritalStatus_Married,...,HasDependents_Yes,LoanPurpose_Auto,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,HasCoSigner_No,HasCoSigner_Yes,Default_0,Default_1
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
255343,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
255344,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
255345,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
255346,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0

In [32]:
final = pd.concat([x,encode_var_df],axis=1)
final

,Age,Income,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education_Bachelor's,Education_High School,Education_Master's,...,HasDependents_Yes,LoanPurpose_Auto,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,HasCoSigner_No,HasCoSigner_Yes,Default_0,Default_1
0,56,85994,80,4,15.23,36,0.44,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1,69,50432,15,1,4.81,60,0.68,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,46,84208,26,3,21.17,24,0.31,0.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,32,31713,0,3,7.07,24,0.23,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,60,20437,8,4,6.51,48,0.73,1.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,19,37979,109,4,14.11,12,0.85,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
255343,32,51953,14,2,11.55,24,0.21,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
255344,56,84820,70,3,5.29,60,0.50,0.0,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
255345,42,85109,40,1,20.90,48,0.44,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
255346,62,22418,113,2,6.73,12,0.48,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0

In [43]:
y=original_data['CreditScore']
x=final[list(final.columns)]
model2=LinearRegression()

model2.fit(x,y)

LinearRegression()

In [44]:
print(model2.coef_)
print(model2.score(x, y))

[-7.26749260e-02 -2.08146250e-05 -1.37643968e-02  1.52373149e-01
  1.26889129e-01  1.06529390e-02 -2.11794641e-01 -6.96657189e-02
  7.79774151e-01 -8.60548837e-01  1.50440404e-01 -1.24844869e+00
 -1.12594557e-01  3.91412880e-01  9.69630364e-01  7.82937208e-01
 -1.99379242e-01 -5.83557966e-01 -1.37090396e-01  1.37090396e-01
  6.86550622e-01 -6.86550622e-01  3.81735254e-01 -6.54528775e-02
 -1.02310237e+00  5.27779370e-01  1.79040620e-01  6.69900368e-01
 -6.69900368e-01  9.28417430e+00 -9.28417430e+00]
0.0013720529299851014

In [13]:
fig = px.scatter(
    original_data,
    x="Age",
    y="LoanAmount",
    title="Loan Amount vs. Credit Score"
)

fig.show()